
REQUEST_TIMEOUT = (60, 180)

MESSAGE_TYPE_INFO = 5
MESSAGE_TYPE_WARNING = 4
MESSAGE_TYPE_ERROR = 3

EXCEPTION_WAIT_SEC = 5

SETTING_STATUS_NAME = 'status'
SETTING_STATUS_PROCESSING = 'processing'
SETTING_STATUS_STOPPED = 'stopped'
SETTING_STATUS_RELOAD = 'reload'
SETTING_STATUS_CLEAN = 'clean'
SETTING_STATUS_PREPARING = 'preparing'
SETTING_STATUS_PREPARED = 'prepared'
SETTING_STATUS_PAUSED = 'paused'

SETTING_REFRESH_DATA_NAME = 'refreshData'
SETTING_REFRESH_DATA_TRUE = '1'
SETTING_REFRESH_DATA_FALSE = '0'

DATA_FOLDER = 'data'

TF_LOG_LEVEL = "2"

TYPE_PHOTO_FRAUD_DETECTION = 1

FDF_PYD_PATH = "./fdf"

STATUS_NONE = 0
STATUS_COMPLETED = 1
