..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\1500964_582939561773943_1828937709_o.jpeg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\20150119_202906.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\Car-Damage-Area.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\coke in photo.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\Date.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\Date_No XMP Included.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\IMG_0381.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\Jeep_Odometer.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\Odometer.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\VehicleOdometer _ data removed from backend.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\VIN-number-windshield.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\vin.jpg"
..\bin\fdf.exe "D:\FDF\fdf-cpp\test\images\FROUD_JPEGS\your-leased-car-has-damage.jpg"
