
from distutils.core import setup
from distutils.extension import Extension

fdf = Extension(
    'fdf',
    sources=['fdf.cpp',
        '../Service/SuspiciousInfo.cpp',
        '../Service/FraudDetectAlgorithm.cpp',
        '../Service/Configuration.cpp',
        '../Photos/Jpeg/BenfordConf.cpp',
        '../Photos/Jpeg/JpegBenfordAlgorithm.cpp',
        '../thirdparty/jpeg-data/jpeg-data.cpp',
        '../thirdparty/jpeg-data/jpeg-marker.cpp',
        '../Photos/Jpeg/ExifConf.cpp',
        '../Photos/Jpeg/JpegExifAlgorithm.cpp',
        '../Photos/All/PcaConf.cpp',
        '../Photos/All/PhotosPcaAlgorithm.cpp',
        '../Photos/Jpeg/JpegTools.cpp',
        '../Photos/Jpeg/QualityConf.cpp',
        '../Photos/Jpeg/JpegQualityAlgorithm.cpp',
        '../Photos/All/CnnConf.cpp',
        '../Photos/All/CnnEnv.cpp',
        '../Photos/All/PhotosCnnAlgorithm.cpp',
        '../Photos/All/InfoConf.cpp',
        '../Photos/All/PhotosInfoAlgorithm.cpp'],
    libraries=['boost_python36', 
        'jpeg',
        'exif',
        'opencv_calib3d',
        'opencv_core',
        'opencv_dnn',
        'opencv_features2d',
        'opencv_flann',
        'opencv_highgui',
        'opencv_imgcodecs',
        'opencv_imgproc',
        'opencv_ml',
        'opencv_objdetect',
        'opencv_photo',
        'opencv_shape',
        'opencv_stitching',
        'opencv_superres',
        'opencv_video',
        'opencv_videoio',
        'opencv_videostab',
        'tensorflow'],
    extra_compile_args=['-std=c++11','-stdlib=libc++', '-I../include/',
        '-I/Users/val/anaconda3/include', '-I./include', '-I/usr/local/include/'],
    extra_link_args=['-stdlib=libc++', '-L../../lib', '-L/usr/local/lib',  
        '-L/Users/val/anaconda3/lib', '-L/Users/val/anaconda3'],
)

setup(
    name='fdf',
    version='0.1',
    ext_modules=[fdf])
